// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkETElj0oYnsEoQFS1W0A1YuwNUlWnwNs',
    appId: '1:29282680012:web:6bdacdbbe57172e8f8d669',
    messagingSenderId: '29282680012',
    projectId: 'testify-4fbbc',
    authDomain: 'testify-4fbbc.firebaseapp.com',
    storageBucket: 'testify-4fbbc.firebasestorage.app',
    measurementId: 'G-BCLZ3N9VPT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnQG_gobJpNSOccEVNstAhYDztFwwlpDY',
    appId: '1:29282680012:ios:82305459c7221532f8d669',
    messagingSenderId: '29282680012',
    projectId: 'testify-4fbbc',
    storageBucket: 'testify-4fbbc.firebasestorage.app',
    iosBundleId: 'com.example.testify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkETElj0oYnsEoQFS1W0A1YuwNUlWnwNs',
    appId: '1:29282680012:web:464ac0a1d3820eabf8d669',
    messagingSenderId: '29282680012',
    projectId: 'testify-4fbbc',
    authDomain: 'testify-4fbbc.firebaseapp.com',
    storageBucket: 'testify-4fbbc.firebasestorage.app',
    measurementId: 'G-SBC3T1QXCL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnQG_gobJpNSOccEVNstAhYDztFwwlpDY',
    appId: '1:29282680012:ios:82305459c7221532f8d669',
    messagingSenderId: '29282680012',
    projectId: 'testify-4fbbc',
    storageBucket: 'testify-4fbbc.firebasestorage.app',
    iosBundleId: 'com.example.testify',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRUClrjJBqjf701_l7DalYXlrGDmkeKjo',
    appId: '1:29282680012:android:80d94ab1001f1f1ef8d669',
    messagingSenderId: '29282680012',
    projectId: 'testify-4fbbc',
    storageBucket: 'testify-4fbbc.firebasestorage.app',
  );

}